### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by AbdishakurAbdiSaidAdan** [JuhieMotiani/Diagnosticc#1]
I have downloaded all the requirements library but I can't run the program 

this is the error 
C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main>python server.py
Traceback (most recent call last):
  File "C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main\server.py", line 4, in <module>
    import prediction
  File "C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main\prediction.py", line 5, in <module>
    model = keras.models.load_model('model/CPN_Model.h5')
  File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\saved_model\load.py", line 108, in load
    meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
  File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: model/CPN_Model.h5\{saved_model.pbtxt|saved_model.pb}

so, please look into it.

**Comment by JuhieMotiani** [comment]
Hello,

Could you please send me the screenshot of the error. I will look into it.

**Comment by AbdishakurAbdiSaidAdan** [comment]
PS C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main> python server.py
        Traceback (most recent call last):

    File "C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main\server.py", line 4, in <module>
    import prediction
    File "C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main\prediction.py", line 5, in <module>
    model = keras.models.load_model("model/CPN_Model.h5")
    File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\save.py", line 205, in 
     load_model
    return saved_model_load.load(filepath, compile, options)
   File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\saved_model\load.py", 
   line 108, in load  meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
   File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site 
   packages\tensorflow\python\saved_model\loader_impl.py", line 118, in parse_saved_model
    raise IOError(
  OSError: SavedModel file does not exist at: model/CPN_Model.h5\{saved_model.pbtxt|saved_model.pb}

**Comment by AbdishakurAbdiSaidAdan** [comment]
Error Displaying

**Comment by AbdishakurAbdiSaidAdan** [comment]
> ```
>        PS C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main> python server.py
>       Traceback (most recent call last):
>      File "C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main\server.py", line 4, in <module>
>      import prediction 
>      File "C:\Users\AbdiShakra\OneDrive\Documents\Diagnosticc-main\prediction.py", line 5, in <module>
>     model = keras.models.load_model("model/CPN_Model.h5")
>    File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\save.py", line 205, in 
>   load_model
>  return saved_model_load.load(filepath, compile, options)
>  File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\saved_model\load.py", 
>  line 108, in load
>  meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
>  File "C:\Users\AbdiShakra\AppData\Local\Programs\Python\Python39\lib\site- 
> packages\tensorflow\python\saved_model\loader_impl.py", line 118, in parse_saved_model
> raise IOError(
>  OSError: SavedModel file does not exist at: model/CPN_Model.h5\{saved_model.pbtxt|saved_model.pb}
> ```
